name: Login to ECR
author: jwalton
description: Login to Amazon ECR.
inputs:
  access-key-id:
    required: false
    description: Access key for IAM User.
  secret-access-key:
    required: false
    description: Secret access key for IAM User.
  region:
    description: AWS Region to use.
    required: false
outputs:
  account:
    description: Amazon account number.
  registry:
    description: ECR registry hostname (e.g. 000000000000.dkr.ecr.us-east-1.amazonaws.com)
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: log-in
  color: orange
