name: Login to ECR
author: jwalton
description: Login to Amazon ECR.
inputs:
  access-key-id:
    description: Access key for IAM User.
  secret-access-key:
    description: Secret access key for IAM User.
  region:
    description: AWS Region to use.
    required: false
outputs:
  account:
    description: Amazon account number.
runs:
  using: node12
  main: 'main.js'
branding:
  icon: log-in
  color: orange
